apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8080