apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: customers-service
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080