name: Staging Deploy Workflow
run-name: Starting to deploy ${{ inputs.service-name }} to staging
on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-version:
        required: true
        type: string
jobs:
  deploy-the-service:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find the value key for helm 
        run: |
          case "${{ inputs.service-name }}" in
            spring-petclinic-api-gateway)
              echo "SERVICE_KEY=apigateway" >> $GITHUB_ENV
              ;;
            spring-petclinic-customers-service)
              echo "SERVICE_KEY=customersservice" >> $GITHUB_ENV
              ;;
            spring-petclinic-vets-service)
              echo "SERVICE_KEY=vetsservice" >> $GITHUB_ENV
              ;;
            spring-petclinic-visits-service)
              echo "SERVICE_KEY=visitsservice" >> $GITHUB_ENV
              ;;
          esac

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

        # check https://github.com/marketplace/actions/deploy-helm-chart-to-aws-eks-cluster
      - name: Deploy Helm to Staging
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3
          cluster-name: petclinic-eks
          config-files: helmchart/staging-values.yaml
          chart-path: helmchart/
          values: database.password="${{ secrets.DB_PASSWORD_BASE64 }}",${{ env.SERVICE_KEY }}.version=${{ inputs.service-version }}
          name: petclinic-staging